# Generated by Django 5.1.4 on 2025-12-24 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaSafetyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("radius_km", models.IntegerField(default=2)),
                ("volunteer_count", models.IntegerField(default=0)),
                ("average_response_time_minutes", models.FloatField(default=0.0)),
                ("total_emergencies", models.IntegerField(default=0)),
                ("resolved_emergencies", models.IntegerField(default=0)),
                ("safety_score", models.IntegerField(default=50)),
                ("score_color", models.CharField(default="yellow", max_length=20)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-safety_score"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_level",
                    models.CharField(
                        choices=[
                            ("general", "General Volunteer"),
                            ("first_aid", "First-Aid Trained"),
                            ("medical", "Medical Professional"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="verifications/ids/"
                    ),
                ),
                (
                    "certification",
                    models.FileField(
                        blank=True, null=True, upload_to="verifications/certs/"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("availability_radius_km", models.IntegerField(default=5)),
                ("total_responses", models.IntegerField(default=0)),
                ("successful_responses", models.IntegerField(default=0)),
                ("average_response_time_minutes", models.FloatField(default=0.0)),
                ("impact_score", models.IntegerField(default=0)),
                ("bio", models.TextField(blank=True)),
                (
                    "specializations",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated specializations",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_volunteers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-impact_score", "-created_at"],
            },
        ),
    ]
