# Generated by Django 5.1.4 on 2025-12-31 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon_class",
                    models.CharField(help_text="Bootstrap icon class", max_length=50),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("milestone", "Milestone"),
                            ("performance", "Performance"),
                            ("special", "Special Event"),
                            ("training", "Training"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        help_text="e.g., 'total_responses', 'avg_response_time'",
                        max_length=50,
                    ),
                ),
                (
                    "requirement_value",
                    models.FloatField(help_text="Threshold to earn badge"),
                ),
                ("points_reward", models.IntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        default="#FFD700", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["badge_type", "requirement_value"],
            },
        ),
        migrations.CreateModel(
            name="ResponderStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_responses",
                    models.IntegerField(
                        default=0, help_text="Total emergencies accepted"
                    ),
                ),
                (
                    "completed_responses",
                    models.IntegerField(
                        default=0, help_text="Successfully completed emergencies"
                    ),
                ),
                (
                    "lives_saved",
                    models.IntegerField(default=0, help_text="Confirmed lives saved"),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        default=0.0, help_text="Average time to accept (minutes)"
                    ),
                ),
                (
                    "average_arrival_time",
                    models.FloatField(
                        default=0.0, help_text="Average time to arrive (minutes)"
                    ),
                ),
                (
                    "fastest_response",
                    models.FloatField(
                        blank=True,
                        help_text="Fastest response time (minutes)",
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=5.0, help_text="Average rating from victims"
                    ),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                (
                    "current_streak",
                    models.IntegerField(default=0, help_text="Consecutive days active"),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                ("total_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                (
                    "badges",
                    models.JSONField(
                        default=list, help_text="List of earned badge IDs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responder_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Responder Statistics",
            },
        ),
    ]
