# Generated by Django 5.1.4 on 2025-12-24 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BystanderGuidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("accident", "Accident"),
                            ("medical", "Medical"),
                            ("fire", "Fire"),
                            ("personal_safety", "Personal Safety"),
                            ("disaster", "Disaster"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("step_number", models.IntegerField()),
                ("instruction", models.TextField()),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, help_text="CSS class for icon", max_length=50
                    ),
                ),
                (
                    "warning",
                    models.TextField(
                        blank=True, help_text="Important warnings or don'ts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["emergency_type", "step_number"],
                "unique_together": {("emergency_type", "step_number")},
            },
        ),
        migrations.CreateModel(
            name="Emergency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emergency_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("accident", "Accident"),
                            ("medical", "Medical"),
                            ("fire", "Fire"),
                            ("personal_safety", "Personal Safety"),
                            ("disaster", "Disaster"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("moderate", "Moderate"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("responder_assigned", "Responder Assigned"),
                            ("responder_en_route", "Responder En Route"),
                            ("responder_arrived", "Responder Arrived"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_address", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "voice_note",
                    models.FileField(
                        blank=True, null=True, upload_to="emergencies/voice/"
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("responder_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("responder_arrived_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("bystander_mode_active", models.BooleanField(default=False)),
                (
                    "bystander_mode_activated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_responder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_emergencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Emergencies",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sos_triggered", "SOS Triggered"),
                            ("responder_notified", "Responder Notified"),
                            ("responder_accepted", "Responder Accepted"),
                            ("responder_declined", "Responder Declined"),
                            ("responder_en_route", "Responder En Route"),
                            ("responder_arrived", "Responder Arrived"),
                            ("bystander_mode_activated", "Bystander Mode Activated"),
                            ("status_updated", "Status Updated"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emergency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="emergencies.emergency",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("notified", "Notified"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("en_route", "En Route"),
                            ("arrived", "Arrived"),
                        ],
                        default="notified",
                        max_length=20,
                    ),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                (
                    "estimated_arrival_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "emergency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="emergencies.emergency",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["distance_km", "-notified_at"],
                "unique_together": {("emergency", "responder")},
            },
        ),
    ]
