# Generated by Django 5.1.4 on 2025-12-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergencies", "0002_pushsubscription_responderlocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bystanderguidance",
            options={"ordering": ["emergency_type", "language", "step_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="bystanderguidance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bystanderguidance",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi"), ("mr", "Marathi")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bystanderguidance",
            unique_together={("emergency_type", "language", "step_number")},
        ),
    ]
