# Generated by Django 5.1.4 on 2025-12-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodule",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload MP4/WebM file directly (Recommended)",
                null=True,
                upload_to="training_videos/",
            ),
        ),
    ]
